//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : TransportSystem
//  @ File Name : Contansts.cs
//  @ Date : 12/17/2013
//  @ Author : khoatd
//
//

using System.ComponentModel;
namespace lhk.POS.Core
{
    public class Constants
    {

    }
}
