//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled Shopping Central
//  @ File Name : GeneralVariable.cs
//  @ Date : 2/22/2013
//  @ Author :  khoatd
//
//

using Core.Domain;
namespace Core.Util
{
    public static class SystemParam
    {
        private static bool m_isLogged;

        public static bool IsLogged
        {
            get { return m_isLogged; }
            set { m_isLogged = value; }
        }

        private static bool m_isOpenTransShift;

        public static bool IsOpenTransShift
        {
            get { return m_isOpenTransShift; }
            set { m_isOpenTransShift = value; }
        }

        private static bool m_isCreating;

        public static bool IsCreating
        {
            get { return SystemParam.m_isCreating; }
            set { SystemParam.m_isCreating = value; }
        }
        private static bool m_isUpdating;

        public static bool IsUpdating
        {
            get { return SystemParam.m_isUpdating; }
            set { SystemParam.m_isUpdating = value; }
        }

        private static bool m_isRemoteState;

        public static bool IsRemoteState
        {
            get { return SystemParam.m_isRemoteState; }
            set { SystemParam.m_isRemoteState = value; }
        }
    }
}
